### PR TITLE
fix: missing example .env variables 

### PR DESCRIPTION
**Pull request by Ketcap**
# Description

Missing example variables for .env file

### CODE REVIEW

**Review by FurkanGM — APPROVED** [review]

**Comment by puskuruk** [comment]
Using `NEXT_` prefix instead of `NEXT` would be more readable

**Comment by Ketcap** [comment]
> Using `NEXT_` prefix instead of `NEXT` would be more readable

That "NEXTAUTH_URL" is used for "next-auth" package it has nothing to do with "next" itself :/ 
https://next-auth.js.org/configuration/options

**Comment by puskuruk** [comment]
> > Using `NEXT_` prefix instead of `NEXT` would be more readable
> 
> 
> 
> That "NEXTAUTH_URL" is used for "next-auth" package it has nothing to do with "next" itself :/ 
> 
> https://next-auth.js.org/configuration/options

I see 🙏

**Review by usirin — APPROVED** [review]
💯 TY, i've been meaning to do this for a long time, procrastinated so much :D

**Pull request merged**
